### ISSUE TITLE
sass import 后条件编译无效

### ISSUE THREAD

**Issue by BlackCubeNo99** [afterwind-io/preprocessor-loader#19]
```scss
/* common.scss */
.test {
  // #!if NODE_ENV === 'production'
  color: red;
  // #!elseif NODE_ENV === 'development'
  color: blue;
  // #!endif
}
```

```scss
/* index.scss */
@import './common.scss'
```

当前 `NODE_ENV` 为 `'development'`，`index.scss` 最终编译后的是 `color: red`。

**Comment by afterwind-io** [comment]
@BlackCubeNo99
我在本地测试了一下你的代码，最终的结果为：

```css
/* common.scss */
.test{ color: red; color: blue; }
```

说明`sass`在处理`@import`导入的文件时，不会经过`webpack`的`loader`处理环节。

这个问题与`sass`的处理逻辑有关，而且从`sass`的视角来看这样做是合理的。建议可以考虑给`sass-loader`寄相关问题确认一下。

P.S. 我本地使用的相关版本：
```
"dependencies": {
    "css-loader": "^6.2.0",
    "sass": "^1.37.0",
    "sass-loader": "^12.1.0",
    "style-loader": "^3.2.1",
    "webpack": "^5.47.1"
    "webpack-preprocessor-loader": "^1.1.4",
},
```
